create table if not exists submissions (
    id bigint generated by default as identity primary key,
    created_at text not null,
    updated_at text,
    edit_count integer not null default 0,
    consent boolean not null default true,
    name text not null,
    phone text not null,
    complex_name text not null,
    existing_dong text not null,
    existing_ho text not null,
    existing_size text not null,
    unit_key text not null unique,
    hope_size_1 text not null,
    hope_size_2 text not null,
    hope_size_3 text not null,
    hope_floor text not null,
    hope_location text not null,
    top_priority text not null,
    memo text
);
create table if not exists edit_logs (
    id bigint generated by default as identity primary key,
    submission_id bigint,
    edited_at text not null,
    old_data text,
    new_data text
);
