-- v0.6 종이설문지 스타일 앱용 새 테이블입니다.
-- 기존 v0.5 테이블과 충돌하지 않도록 새 이름을 사용합니다.

drop table if exists survey_edit_logs_v06 cascade;
drop table if exists survey_submissions_v06 cascade;

create table survey_submissions_v06 (
    id bigint generated by default as identity primary key,
    created_at text,
    updated_at text,
    edit_count integer default 0,
    consent boolean default true,

    owner_name text,
    signature_name text,
    address text,
    phone text,
    property_type text,
    existing_dong text,
    existing_ho text,
    current_size text,
    current_size_other text,
    current_size_final text,
    unit_key text unique,

    family_plan text,
    family_count integer,
    plan_preference text,
    room_count text,
    household_split text,

    factor_rank_1 text,
    factor_rank_2 text,
    factor_rank_3 text,
    factor_rank_4 text,
    factor_rank_5 text,

    hope_size text,

    parking text,
    parking_other text,

    community_rank_1 text,
    community_rank_2 text,
    community_rank_3 text,
    community_rank_4 text,
    community_rank_5 text,
    community_other text,

    landscape_rank_1 text,
    landscape_rank_2 text,
    landscape_rank_3 text,
    landscape_rank_4 text,
    landscape_rank_5 text,
    landscape_other text,

    semi_residential text[],
    semi_residential_other text,

    final_opinion text,

    attachment_path text,
    attachment_name text,
    attachment_type text,
    attachment_size bigint
);

create table survey_edit_logs_v06 (
    id bigint generated by default as identity primary key,
    submission_id bigint,
    edited_at text,
    old_data text,
    new_data text
);

alter table survey_submissions_v06 disable row level security;
alter table survey_edit_logs_v06 disable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant all on table survey_submissions_v06 to anon, authenticated, service_role;
grant all on table survey_edit_logs_v06 to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- 첨부파일 저장용 비공개 버킷 생성
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('survey-attachments-v06', 'survey-attachments-v06', false, 52428800, null)
on conflict (id) do update
set public = false,
    file_size_limit = 52428800;

notify pgrst, 'reload schema';
