-- Supabase SQL Editor에서 실행하세요.
-- 기존 v0.3 테이블이 있어도 새 컬럼을 추가하는 업데이트 SQL입니다.

create table if not exists submissions (
    id bigint generated by default as identity primary key,
    created_at text not null,
    updated_at text,
    edit_count integer not null default 0,
    consent boolean not null default true,
    name text not null,
    existing_dong text not null,
    existing_ho text not null,
    existing_size text not null,
    unit_key text not null unique
);

create table if not exists edit_logs (
    id bigint generated by default as identity primary key,
    submission_id bigint,
    edited_at text not null,
    old_data text,
    new_data text
);

alter table submissions add column if not exists family_plan text;
alter table submissions add column if not exists family_count integer;
alter table submissions add column if not exists plan_preference text;
alter table submissions add column if not exists room_count text;
alter table submissions add column if not exists household_split text;

alter table submissions add column if not exists factor_rank_1 text;
alter table submissions add column if not exists factor_rank_2 text;
alter table submissions add column if not exists factor_rank_3 text;
alter table submissions add column if not exists factor_rank_4 text;
alter table submissions add column if not exists factor_rank_5 text;

alter table submissions add column if not exists hope_size text;

alter table submissions add column if not exists parking text;
alter table submissions add column if not exists parking_other text;

alter table submissions add column if not exists community_rank_1 text;
alter table submissions add column if not exists community_rank_2 text;
alter table submissions add column if not exists community_rank_3 text;
alter table submissions add column if not exists community_rank_4 text;
alter table submissions add column if not exists community_rank_5 text;
alter table submissions add column if not exists community_other text;

alter table submissions add column if not exists landscape_rank_1 text;
alter table submissions add column if not exists landscape_rank_2 text;
alter table submissions add column if not exists landscape_rank_3 text;
alter table submissions add column if not exists landscape_rank_4 text;
alter table submissions add column if not exists landscape_rank_5 text;
alter table submissions add column if not exists landscape_other text;

alter table submissions add column if not exists semi_residential text;
alter table submissions add column if not exists semi_residential_other text;

alter table submissions add column if not exists memo text;

-- v0.3에서 쓰던 컬럼이 있는 경우를 대비해 남겨둡니다.
alter table submissions add column if not exists phone text;
alter table submissions add column if not exists complex_name text;
alter table submissions add column if not exists hope_size_1 text;
alter table submissions add column if not exists hope_size_2 text;
alter table submissions add column if not exists hope_size_3 text;
alter table submissions add column if not exists hope_floor text;
alter table submissions add column if not exists hope_location text;
alter table submissions add column if not exists top_priority text;
